export const texts = {
    es: {
      title: "Compra de Entradas",
      description: "Selecciona tus entradas, moneda y elige el método de pago",
      selectLanguage: "Seleccionar Idioma",
      selectCurrency: "Seleccionar Moneda",
      tickets: "Número de Entradas",
      paymentMethod: "Método de Pago",
      creditCard: "Tarjeta de Crédito",
      mercadoPago: "Mercado Pago",
      name: "Nombre en la Tarjeta",
      cardNumber: "Número de Tarjeta",
      expiry: "Fecha de Vencimiento",
      cvc: "CVC",
      total: "Total",
      pay: "Pagar Ahora",
      orderSummary: "Resumen de la Orden",
      savePaymentInfo: "Guardar información de pago",
      processing: "Procesando pago...",
      invalidCard: "Número de tarjeta inválido",
      invalidExpiry: "Fecha de vencimiento inválida",
      invalidCVC: "CVC inválido",
    },
    en: {
      title: "Ticket Purchase",
      description: "Select your tickets, currency and choose the payment method",
      selectLanguage: "Select Language",
      selectCurrency: "Select Currency",
      tickets: "Number of Tickets",
      paymentMethod: "Payment Method",
      creditCard: "Credit Card",
      mercadoPago: "Mercado Pago",
      name: "Name on Card",
      cardNumber: "Card Number",
      expiry: "Expiry Date",
      cvc: "CVC",
      total: "Total",
      pay: "Pay Now",
      orderSummary: "Order Summary",
      savePaymentInfo: "Save payment information",
      processing: "Processing payment...",
      invalidCard: "Invalid card number",
      invalidExpiry: "Invalid expiry date",
      invalidCVC: "Invalid CVC",
    },
    pt: {
      title: "Compra de Ingressos",
      description:
        "Selecione seus ingressos, moeda e escolha o método de pagamento",
      selectLanguage: "Selecionar Idioma",
      selectCurrency: "Selecionar Moeda",
      tickets: "Número de Ingressos",
      paymentMethod: "Método de Pagamento",
      creditCard: "Cartão de Crédito",
      mercadoPago: "Mercado Pago",
      name: "Nome no Cartão",
      cardNumber: "Número do Cartão",
      expiry: "Data de Validade",
      cvc: "CVC",
      total: "Total",
      pay: "Pagar Agora",
      orderSummary: "Resumo do Pedido",
      savePaymentInfo: "Salvar informações de pagamento",
      processing: "Processando pagamento...",
      invalidCard: "Número de cartão inválido",
      invalidExpiry: "Data de validade inválida",
      invalidCVC: "CVC inválido",
    },
    fr: {
      title: "Achat de Billets",
      description:
        "Sélectionnez vos billets, la devise et choisissez le mode de paiement",
      selectLanguage: "Sélectionner la Langue",
      selectCurrency: "Sélectionner la Devise",
      tickets: "Nombre de Billets",
      paymentMethod: "Mode de Paiement",
      creditCard: "Carte de Crédit",
      mercadoPago: "Mercado Pago",
      name: "Nom sur la Carte",
      cardNumber: "Numéro de Carte",
      expiry: "Date d'Expiration",
      cvc: "CVC",
      total: "Total",
      pay: "Payer Maintenant",
      orderSummary: "Résumé de la Commande",
      savePaymentInfo: "Sauvegarder les informations de paiement",
      processing: "Traitement du paiement...",
      invalidCard: "Numéro de carte invalide",
      invalidExpiry: "Date d'expiration invalide",
      invalidCVC: "CVC invalide",
    },
  };